# Generated by Django 5.0 on 2023-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
