# Generated by Django 5.0 on 2023-12-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_image',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
